config/routes.rb
Ebs2s3::Application.routes.draw do
  resources :jobs do
    resources :events
  end
  resource :account, :controller => "users"
  resources :volumes
  resources :users
  resource :user_session
  root :to => "jobs#index"

  match 'jobs/:id/schedule' => 'jobs#schedule'

end

app/models/job.rb
#
# Copyright 2011, Andrew Fulcher
#
# This file is part of Ebs2s3.
#
# Ebs2s3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Ebs2s3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ebs2s3.  If not, see <http://www.gnu.org/licenses/>.
#

class Job < ActiveRecord::Base
  has_many :events
end

app/controllers/jobs_controller.rb
#
# Copyright 2011, Andrew Fulcher
#
# This file is part of Ebs2s3.
#
# Ebs2s3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Ebs2s3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ebs2s3.  If not, see <http://www.gnu.org/licenses/>.
#

class JobsController < ApplicationController
  before_filter :require_user

  def index
    @jobs = Job.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @jobs }
    end
  end

  def show
    @job = Job.find(params[:id])
    
    aws_key = APP_CONFIG["aws_key"]
    secret = APP_CONFIG["aws_secret"]
    region = APP_CONFIG["aws_region"]
    
    begin
      conn = Fog::Compute.new(:provider => 'AWS', :aws_access_key_id => aws_key, :aws_secret_access_key => secret, :region => region)
      @snapshots = conn.snapshots.all('volume-id' => @job[:ebsvol])
    rescue
      @snapshots = []
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @job }
    end
  end

  def new
    @job = Job.new(:ebsvol => params[:ebsvol])

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @job }
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        self.schedule(@job)
        format.html { redirect_to(@job, :notice => 'Job was successfully created.') }
        format.xml  { render :xml => @job, :status => :created, :location => @job }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        self.schedule(@job)
        format.html { redirect_to(@job, :notice => 'Job scheduled successfully.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @job.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @job = Job.find(params[:id])
    
    # Unschedule tasks if attached
    tasks = $scheduler.find_by_tag(params[:id]).each{|t| t.unschedule }
    @job.destroy

    respond_to do |format|
      format.html { redirect_to(jobs_url) }
      format.xml  { head :ok }
    end
  end
  
  def schedule(job)
    
    # Unschedule task if it already exists
    tasks = $scheduler.find_by_tag(job.id).each{|t| t.unschedule }
    
    # And re-schedule
    $scheduler.cron job.cronline, :tags => job.id do
      self.delete_old_snapshots(job.ebsvol,job.id,job.copies)
      self.backup(job.ebsvol,job.id)
    end
    
  end
  
  def delete_old_snapshots(ebsvol,tag,copies)
    
    aws_key = APP_CONFIG["aws_key"]
    secret = APP_CONFIG["aws_secret"]
    region = APP_CONFIG["aws_region"]
    
    conn = Fog::Compute.new(:provider => 'AWS', :aws_access_key_id => aws_key, :aws_secret_access_key => secret, :region => region)
    snapshots = conn.snapshots.map{|a| a if (a.volume_id == ebsvol && a.description == "Job id: #{tag}")}.compact
    
    unless snapshots.empty?
      sorted_snaps = snapshots.sort_by{|a| a.created_at}
      while sorted_snaps.count > copies
        snap_to_del = sorted_snaps.shift
        puts "Deleting snapshot #{snap_to_del.id}"
        snap_to_del.destroy
      end
    end
    
  end
  
  def backup(ebsvol,tag)
    
    aws_key = APP_CONFIG["aws_key"]
    secret = APP_CONFIG["aws_secret"]
    region = APP_CONFIG["aws_region"]
    
    puts "Creating snapshot of volume #{ebsvol} with id #{tag}"
    conn = Fog::Compute.new(:provider => 'AWS', :aws_access_key_id => aws_key, :aws_secret_access_key => secret, :region => region)
    conn.create_snapshot(ebsvol,"Job id: #{tag}")
    
  end
  
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Job name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label "Volume name (e.g. vol-xxxxxx)" %><br />
    <%= f.text_field :ebsvol %>
  </div>
  <div class="field">
    <%= f.label "Cron line (e.g. 10 10 * * *)" %><br />
    <%= f.text_field :cronline %>
  </div>
  <div class="field">
    <%= f.label "Number of previous backups to retain" %><br />
    <%= f.text_field :copies %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="container">
  <%= render :partial => 'layouts/navbar' %>
  <div class="thin-pad">
    <h2>Editing job</h2>
    <div class="main-page">
      <%= render 'form' %>
      
      <%= link_to 'Show', @job %> |
      <%= link_to 'Back', jobs_path %>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <%= render :partial => 'layouts/navbar' %>
  <div class="thin-pad">
    <h2>All jobs</h2>
    <div class="main-page">
      <table>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Ebsvol</th>
          <th>Cronline</th>
          <th>Copies</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.name %></td>
          <td><%= job.description %></td>
          <td><%= job.ebsvol %></td>
          <td><%= job.cronline %></td>
          <td><%= job.copies %></td>
          <td><%= link_to 'Show', job %></td>
          <td><%= link_to 'Edit', edit_job_path(job) %></td>
          <td><%= link_to 'Destroy', job, :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
      <% end %>
      </table>
      
      <br />
      
      <%= link_to 'New Job', volumes_path %>
    
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <%= render :partial => 'layouts/navbar' %>
  <div class="thin-pad">
    <h2>New job</h2>
    <div class="main-page">
      <%= render 'form' %>
      <br />
      <%= link_to 'Back', volumes_path %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <%= render :partial => 'layouts/navbar' %>
  <div class="thin-pad">
    <h2><%= @job.name %></h2>
    <div class="main-page">
      <p id="notice"><%= notice %></p>
      
      <p>
        <b>Name:</b>
        <%= @job.name %>
      </p>
      
      <p>
        <b>Description:</b>
        <%= @job.description %>
      </p>
      
      <p>
        <b>Ebsvol:</b>
        <%= @job.ebsvol %>
      </p>
      
      <p>
        <b>Cronline:</b>
        <%= @job.cronline %>
      </p>
      
      <p>
        <b>Copies:</b>
        <%= @job.copies %>
      </p>
      
      
      <%= link_to 'Edit', edit_job_path(@job) %> |
      <%= link_to 'Back', jobs_path %>
      <br></br>
      <h3>All snapshots</h3>
      <% unless @snapshots.empty? %>
      <table>
        <tr>
          <th>Id</th>
          <th>Progress</th>
          <th>Created</th>
          <th>State</th>
          <th>Size</th>
        </tr>
      
      <% @snapshots.each do |snap| %>
        <tr>
          <td><%= snap.id %></td>
          <td><%= snap.progress %></td>
          <td><%= snap.created_at %></td>
          <td><%= snap.state %></td>
          <td><%= snap.volume_size %></td>
        </tr>
      <% end %>
      </table>
      <% end %>
    </div>
  </div>
</div>