config/routes.rb
Ebs2s3::Application.routes.draw do
  resources :jobs do
    resources :events
  end
  resource :account, :controller => "users"
  resources :volumes
  resources :users
  resource :user_session
  root :to => "jobs#index"

  match 'jobs/:id/schedule' => 'jobs#schedule'

end

app/models/user.rb
#
# Copyright 2011, Andrew Fulcher
#
# This file is part of Ebs2s3.
#
# Ebs2s3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Ebs2s3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ebs2s3.  If not, see <http://www.gnu.org/licenses/>.
#

class User < ActiveRecord::Base
  acts_as_authentic
end

app/controllers/users_controller.rb
#
# Copyright 2011, Andrew Fulcher
#
# This file is part of Ebs2s3.
#
# Ebs2s3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Ebs2s3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ebs2s3.  If not, see <http://www.gnu.org/licenses/>.
#

class UsersController < ApplicationController
  
  unless User.all.empty?
    before_filter :require_user
  end

  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default jobs_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/views/users/_form.erb
<%= form.label :login %><br />
<%= form.text_field :login %><br />
<br />
<%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
<%= form.password_field :password %><br />
<br />
<%= form.label :password_confirmation %><br />
<%= form.password_field :password_confirmation %><br />

app/views/users/edit.html.erb
<div class="container">
  <%= render :partial => 'layouts/navbar' %>
  <div class="thin-pad">
    <h2>Edit My Account</h2>
    
    <% form_for @user, :url => account_path do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= render :partial => "form", :object => f %>
      <%= f.submit "Update" %>
    <% end %>
    
    <br /><%= link_to "Create a new account", new_account_path %>
  </div>
</div>

app/views/users/new.html.erb
<% unless @current_user.nil? %>
  <div class="container">
    <%= render :partial => 'layouts/navbar' %>
    <div class="thin-pad">
      <h2>Create new user</h2>
      
      <% form_for @user, :url => account_path do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= render :partial => "form", :object => f %>
        <%= f.submit "Create" %>
      <% end %>
    </div>
  </div>
<% else %>
  <%= stylesheet_link_tag ('login.css') %>
  <div id="floater"></div>
    <div id="centered">
      <div class="first-login-box">
        <h2>Create new user</h2>
        
        <% form_for @user, :url => account_path do |f| %>
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <%= render :partial => "form", :object => f %>
          <%= f.submit "Create" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<p>
  <b>Login:</b>
  <%=h @user.login %>
</p>

<%= link_to 'Edit', edit_account_path %>