config/routes.rb
Ebs2s3::Application.routes.draw do
  resources :jobs do
    resources :events
  end
  resource :account, :controller => "users"
  resources :volumes
  resources :users
  resource :user_session
  root :to => "jobs#index"

  match 'jobs/:id/schedule' => 'jobs#schedule'

end

app/models/user_session.rb
#
# Copyright 2011, Andrew Fulcher
#
# This file is part of Ebs2s3.
#
# Ebs2s3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Ebs2s3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ebs2s3.  If not, see <http://www.gnu.org/licenses/>.
#

class UserSession < Authlogic::Session::Base
  
  # Rails 3 fix
  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
end

app/controllers/user_sessions_controller.rb
#
# Copyright 2011, Andrew Fulcher
#
# This file is part of Ebs2s3.
#
# Ebs2s3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Ebs2s3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ebs2s3.  If not, see <http://www.gnu.org/licenses/>.
#

class UserSessionsController < ApplicationController
  
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default jobs_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
  
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<%= stylesheet_link_tag ('login.css') %>
<div id="floater"></div>
<div id="centered">
    <% if User.all.empty? %>
      <div class="first-login-box">
        <h2>Welcome to EBS-2-S3</h2>
        <h4>
          To complete setup, you'll need to create an admin user.  To perform this step, click
          <%= link_to ' here', new_user_path %>
        </h4>
      </div>
    <% else %>
      <div class="login-box">
        <h2>EBS-2-S3</h2>
        <% form_for @user_session, :url => user_session_path do |f| %>
          <% if @user_session.errors.any? %>
            <div id="error_explanation">
              <ul>
              <% @user_session.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <%= f.label :login %><br />
          <%= f.text_field :login %><br />
          <br />
          <%= f.label :password %><br />
          <%= f.password_field :password %><br />
          <br />
          <%= f.check_box :remember_me %><%= f.label :remember_me %><br />
          <br />
          <%= f.submit "Login" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>